### ISSUE TITLE
Feature | Computed Properties

### ISSUE THREAD

**Issue by WojciechSkirlo** [WojciechSkirlo/docs#8]
Add translate to the [Computed Properties](https://polite-cranachan-4a25ff.netlify.app/guide/essentials/computed.html) page.

https://polite-cranachan-4a25ff.netlify.app/guide/essentials/computed.html

**Comment by andrzejrumak** [comment]
I think that better translation for computed properties would be "właściwości obliczane" then "obliczeniowe" and I translated it in this way.
